### PR TITLE
Add indexOf method

### PR DESCRIPTION
**Pull request by 593273894**
The String.prototype.indexOf is not unicode-compatible, so we need a stringz.indexOf.

### CODE REVIEW

**Comment by sallar** [comment]
Hi! thanks @593273894. the coverage is not 100%. can you please check that as well?

**Comment by sallar** [comment]
Thanks! One last request. Please add docs to README.md so I can merge and publish this!

**Comment by 593273894** [comment]
I added a test. Now They are passed.

**Comment by 593273894** [comment]
Ok, I will do that soon.

**Pull request merged**
